apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: compportiq

commonLabels:
  app.kubernetes.io/part-of: compportiq
  app.kubernetes.io/managed-by: kustomize

resources:
  - namespace.yaml
  - service-account.yaml
  - configmap.yaml
  - api-deployment.yaml
  - web-deployment.yaml
  - services.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
  - network-policy.yaml

